# Generated by Django 3.2.6 on 2021-08-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_level', models.CharField(choices=[('P', 'Professional'), ('PG', 'Post Graduate'), ('D', 'Degree'), ('DP', 'Diploma'), ('U', 'Under Graduate'), ('O', 'Other')], max_length=120)),
                ('type', models.CharField(choices=[('P', 'Professional'), ('PG', 'Post Graduate'), ('D', 'Degree'), ('DP', 'Diploma'), ('U', 'Under Graduate'), ('O', 'Other')], max_length=120)),
                ('completion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('major', models.CharField(max_length=120)),
                ('completion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('S', 'School'), ('C', 'Company')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('proficiency', models.CharField(choices=[(100, 'Professional'), (80, 'Advanced'), (60, 'Intermediate'), (40, 'Junior'), (20, 'Beginner')], max_length=19, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainees.fields')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('certifications', models.ManyToManyField(to='trainees.Certification')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainees.education')),
                ('skills', models.ManyToManyField(to='trainees.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('S', 'Senior Developer'), ('J', 'Junior Developer'), ('A', 'Apprentice Developer'), ('O', 'Other')], max_length=1)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainees.establishment')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainees.establishment'),
        ),
        migrations.AddField(
            model_name='certification',
            name='awarded_by',
            field=models.ManyToManyField(to='trainees.Establishment'),
        ),
    ]
