# Generated by Django 3.2.6 on 2021-08-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_proficiency'),
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='skills.Skill'),
        ),
    ]
