# Generated by Django 3.2.6 on 2021-08-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        ('skills', '0003_alter_skill_proficiency'),
        ('trainees', '0002_alter_trainee_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='certifications',
            field=models.ManyToManyField(null=True, to='certifications.Certification'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.Skill'),
        ),
    ]
