# Generated by Django 3.2.6 on 2021-08-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        ('trainees', '0003_auto_20210823_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='certifications',
            field=models.ManyToManyField(to='certifications.Certification'),
        ),
    ]
