# Generated by Django 3.2.6 on 2021-08-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_level', models.CharField(choices=[('P', 'Professional'), ('PG', 'Post Graduate'), ('D', 'Degree'), ('DP', 'Diploma'), ('U', 'Under Graduate'), ('O', 'Other')], max_length=120)),
                ('type', models.CharField(choices=[('P', 'Professional'), ('PG', 'Post Graduate'), ('D', 'Degree'), ('DP', 'Diploma'), ('U', 'Under Graduate'), ('O', 'Other')], max_length=120)),
                ('completion', models.DateField()),
                ('awarded_by', models.ManyToManyField(to='utils.Establishment')),
            ],
        ),
    ]
