# Generated by Django 3.2.6 on 2021-08-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('proficiency', models.CharField(choices=[(100, 'Professional'), (80, 'Advanced'), (60, 'Intermediate'), (40, 'Junior'), (20, 'Beginner')], max_length=19, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.fields')),
            ],
        ),
    ]
