# Generated by Django 3.2.6 on 2021-08-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('Professional', 100), ('Advanced', 80), ('Intermediate', 60), ('Junior', 40), ('Beginner', 20)], max_length=19, null=True),
        ),
    ]
