# Generated by Django 3.2.6 on 2021-08-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[(100, 'Professional'), (80, 'Advanced'), (60, 'Intermediate'), (40, 'Junior'), (20, 'Beginner')], max_length=19, null=True),
        ),
    ]
